- can.config.js
- components/Card/Card.styled.ts
- components/Card/Card.tsx
- components/Figure/Figure.styled.ts
- components/Figure/Figure.tsx
- package-lock.json
- package.json
- Update config.
- Breakout Figure component from Card.
- Add progressive load with low quality image placeholders.
> Merge acwiley for stress testing.

- package-lock.json
- package.json
- This updates Clover IIIF to resolve a responsive bug showing More Information toggle when no Clover navigator is necessary.
- Updates IIIF Commons (vault/parser) libraries to latest
> Update Clover, Parser.

- pages/about.tsx
Fixes typo.
Very cool project you have here👍
> fix typo IIF->IIIF

- components/Map/Map.styled.tsx
- components/Map/Map.tsx
- pages/map.tsx
- services/getFeatures.ts
Fixes map issues so that center and zoom fitBounds.
N/A
> Fix state bug where map doesn't work every other time it's routed to.

- .gitignore
I don't feel like we should have these two files being ignored. Were these lines included by accident?
> Remove custom config ignores.

- components/Map/Map.tsx
- config/.default/options.default.json
- config/options.sample.json
- pages/about.tsx
This adds some extensibility for maps by adding a new prop to the map options that get passed to the Map component.
> Init support for multiple maps.

- services/build/aggregate.js
- services/build/facets.js
- services/build/slug.js
Addresses [Issue 31](https://github.com/mathewjordan/canopy-iiif/issues/31).
> Improve slugging ⚾ 

- .github/workflows/aggregate.yml
- package-lock.json
- package.json
- pages/works/[slug].tsx
- services/iiif/constructors/collection.js
_Please include a summary of the changes and the related issue. Please also include relevant motivation and context._
> Add test-builds.

- components/Map/Map.styled.tsx
- components/Map/Map.tsx
- components/Map/MarkerClusterGroup.tsx
- package-lock.json
- package.json
Addresses [Issue 132](https://github.com/canopy-iiif/canopy-iiif/issues/132) and adds marker clustering when more than 1 navPlace feature is associated with a single location.
> Marker cluster grouping

- pages/about/documentation.mdx
_Please include a summary of the changes and the related issue. Please also include relevant motivation and context._
> Add note about .env variables.

- pages/index.tsx
Addresses Issue-139: https://github.com/canopy-iiif/canopy-iiif/issues/139
While this should fix things, let me know if you feel like it could be more clear.
> Address Issue-139.

- config/canopy.json
- src/lib/build/aggregate.js
- src/lib/build/facets.js
- src/lib/build/request.js
- src/lib/build/thumbnail.js
- src/lib/iiif/constructors/collection.js
- src/lib/iiif/image.js
- src/lib/seo.ts
- src/lib/utils.ts
- src/pages/_app.tsx
- src/pages/index.tsx
This revises the build of canopy to work a little more cleanly with promises and updates thumbnail generation for Manifests not having a thumbnail property at manifest.thumbnail or in items[0].thumbnail (first Canvas).
A thumbnail will be generated if a the first canvas has an annotation.body.type of **Image**. Affordance for other types should be considered in the future.
https://github.com/canopy-iiif/canopy-iiif/blob/45bb977b4247ec2e2d21aa6dabfe8263b993c912/src/lib/build/thumbnail.js#L21-L33
The thumbnail for the Canvas is requested using a Vault helper `getBestThumbnailAtSize` in `src/lib/iiif/image.js`.
https://github.com/canopy-iiif/canopy-iiif/blob/45bb977b4247ec2e2d21aa6dabfe8263b993c912/src/lib/iiif/image.js#L3-L14
To better chunk these requests on large collections, this now …
> Adjust build and generation of thumbnails.

- config/locales/ptBR.json
Add Brazilian Portuguese locale.
> Add Brazilian Portuguese locale

- src/lib/build/aggregate.js
- src/lib/build/facets.js
This fix allows the facet Collection writing that occurs on build to continue even if a Manifest is not found from its doc index matching. Additionally, logging has been added both for successful writing of these .json files in the `public/` directory and for error reporting to aid in tracing of failed creations.
Success example:
```
...
Chunk (19/19)
✓ https://digital.lib.utk.edu/assemble/manifest/rftaart/95 ➜ 200
✓ https://digital.lib.utk.edu/assemble/manifest/rftaart/96 ➜ 200
182/182 Manifests(s) retrieved successfully.
Creating facets as IIIF Collections...
↓ /api/facet/subject/wildfires.json 
↓ /api/facet/subject/evacuation-of-civilians.json 
↓ /api/facet/subject/disaster-relief.json 
↓ /api/facet/subject/social-service.json 
↓ /api/facet/subject/covid-19-pandemic-2020.json 
↓ …
```
> Add defensiveness and logging for facet Collection writing.

- config/.default/options.default.json
- config/options.sample.json
- src/components/Map/Map.tsx
Moves hardcoded bits out of Map so that you can customize the marker from config.
> Break out hardcoded leaflet defaults into config.

- next-sitemap.config.js
- src/pages/map.tsx
This addresses [Issue-166](https://github.com/canopy-iiif/canopy-iiif/issues/166) and does a little more cleanup.
> Address Issue-166.

- .stackblitzrc
- README.md
Adds configuration for [StackBlitz demo environment](https://stackblitz.com/fork/github/canopy-iiif/canopy-iiif)
@mathewjordan Added the StackBlitz badge here as well, but maybe it's too messy.  Will leave up to you whether to include or not...
> Add StackBlitz config

- content/about/example.mdx
- package-lock.json
- package.json
- src/components/MDX/Image.tsx
- src/components/MDX/Scroll.tsx
- src/components/MDX/index.tsx
- src/components/Viewer/Image.tsx
- src/components/Viewer/Scroll.tsx
This updates the Clover dependency to allow user of Image and Scroll components. MDX wrappers have been created for each. I opted not to document Scroll quite yet as it (in beta) still needs some cleanup before we go full blast with it.
See `/about/example` for rendering of Image.
> Update Clover, include new components.

- src/components/Header/Header.tsx
This reincorporates `next/link` in the header to more smartly resolve href navigation.
> Fix homepage link in header.

- .github/workflows/build.yml
- next-env.d.ts
- package-lock.json
- package.json
Updates packages to address vulnerability issues and updates builds and tests to use npm 18.  Weirdly, the actual static build action has always been on 18 which makes this all pretty funny.
Many of the changes here were breaking with major semantic version jumps but:
1. tests pass
2. i haven't seen an issue yet
> Force vulnerability fixes.

- .github/workflows/build.yml
- next-env.d.ts
- package-lock.json
- package.json
This reverts commit fe903629424de7c1b00659bbe676d71d017b04d5.
_Please include a summary of the changes and the related issue. Please also include relevant motivation and context._
> Revert "Force vulnerability fixes. (#214)"
