canopy-iiif/canopy-iiif

pages/api/facet/[label]/[value].ts
services/build/canopy.js
services/iiif/constructors/collection.js
services/iiif/image.js

1. Adds a service to get a representative image from a canvas based on a requested image size. 
2. Generates heroes from these images rather than the thumbnail.
3. Modifies build to include thumbnails in the manifest build objects so they can be served to bloom sliders.
4. Modifies api views to include thumbnails.
1. This does not address thumbnails on works page, but I'll take care of that next.  That still attempts to use the `id` of the body on the annotation page of the annotation on the initial canvas.
2. The getService stuff assumes image 2.  Need to add stuff for image 3.  Do we have a good fixture for testing that?

Representative image

---

README.md

This just updates readme to fit the more current config setup and points folks to the `/about` page in the demo for more information.
- [#] 📘 **Documentation update**

Refine configruation section of readme.

---

components/Card/Card.styled.ts
components/Search/Search.styled.ts
components/Viewer/Slider.styled.ts

This addresses  a few minor styling issues:
- Bloom now works better in Dark mode, adds a row/line limit of 3 to to item labels and uses an ellipsis for text overflow
- Search bar grows across the top no longer being confined by a max width
- Cards have an overflow hidden now to help with display in situations where the computed Canvas and Annotation body aspect ratio does not actually match the resource.

Style refinements on Sliders, Cards, and Search input.

---

components/Facets/Modal.styled.ts

This work adds a baseline overflow scroll to the the facet modal body, allowing both the modal Header and Footer to be visible at all times, and for body content for facets to scroll within the remaining space. This should enhance usability in all viewports, allowing for quicker toggling to Clear all, View Results and Close buttons of the modal.
Default view
Overflow of Body (Dimensions expanded)

Add overflow to facet modal body.

---

.github/workflows/aggregate.yml
canopy.js
config/.fixtures/canopy.presentation-2.json
config/.fixtures/canopy.presentation-3.json
services/config.js

Adds some baseline github actions for testing Canopy prebuilds. This now will test prebuild process on sample Presentation 2.x and 3.x IIIF Collections.

Test new actions.

---

components/Map/Map.tsx

This addresses a bug where if you use the map route without manifests with matching navPlace elements an empty array would be passed to `fitbounds` resulting in an error when state updates.
This ensures `defaultbounds` are used in that case.
There may be a better way to do this.

If bounds empty, use default bounds.

---

components/Hero/Hero.tsx
components/Viewer/Viewer.tsx
package-lock.json
package.json
pages/works/[slug].tsx

This is maintenance work to upgrade packages and prune out unnecessary ones.
- Vault and Vault Helpers have been removed. We now use `@iiif/parser/upgrade` to handle the post-fetch conversion from Presentation 2.x to Presentation 3.0. This should be a bit lighter as we don't need the Vaulty bells and whistles.
- Clover has been updated, now supporting `placeholderCanvas` along with a few small bug fixes.
- Swiper was updated and  small type issue was addressed there.
- Other package updates are routine maintenance.

Prune packages, update outdated.

---

config/locales/nb_NO.json
config/locales/nn_NO.json
config/locales/no.json

Improve the Norwegian translation of the basic UI. Add `nb_NO.json` and `nn_NO.json`, since Norwegian is one spoken language, but with two written forms.
Related to #18, #20.
Norwegian is bit of a complicated language. It is one language with two equal written forms, Bokmål and Nynorsk. `no` is often the default and uses in most cases "bokmål". `nb_NO` (bokmål) and `nn_NO` (nynorsk) would be the precise language codes to use. `no` is therefore more precisely `nb_NO`. 
So, sorry @mathewjordan, Norwegian is one of the more annoying languages to translate... Kept `no`, as it might be needed for browser language detection later?

Improve basic norwegian translation

---

config/.default/options.default.json
config/options.sample.json
pages/about/documentation.mdx
services/search/documents.ts
types/canopy.ts

This update the configuration FlexSearch to be centralized in the options.json `search.flexSearch` property. Doing this makes the FlexSearch configuration easily customizable by the end user without needing to touch any core canopy code.
I additionally created basic documentation for this.

Breakout FlexSearch configuration to options.json.

---

components/Work/Inner.styled.ts

This adds a max-height (relative to the global rem) to any rendered HTML markup `<img/>` within a IIIF Manifest. This accounts for `summary`, `metadata`, and `requiredStatement` properties according to https://iiif.io/api/presentation/3.0/#45-html-markup-in-property-values.

Add max-height to IIIF Manifest HTML markup <img/>.

---

pages/works/[slug].tsx

This work adds the Related component to the subfooter of a `/works` page, rendering Bloom sliders sourced internal facet API routes that return IIIF Collections.

Add Related component to work page.

---

config/.default/canopy.default.json
config/.default/options.default.json
config/canopy.sample.json
config/options.sample.json
package-lock.json
package.json
pages/_app.tsx
pages/about/documentation.mdx
pages/works/[slug].tsx
services/build/aggregate.js
services/iiif/image.js
services/seo.ts
types/canopy.ts

This adds basic SEO coverage across all page routes in Canopy. As of right now, the `/work/...` routes will have unique properties built from the respective Manifest and all other routes will use a default that is sourced from baseline configuration information for the label, summary, and featured canopy.json properties.
I feel this work can be iterative and we can expand on default as needed.

Add baseline OpenGraph meta properties.

---

pages/index.tsx
pages/works/[slug].tsx
services/build/aggregate.js
services/seo.ts
types/canopy.ts

This adds some wide (maybe dirty) concatenation of env vars to create `baseUrl`. Including this will be useful for canopy-iiif instances available at `http://example.org` as well as `http://example.org/custom-base-path`.
Note: There still may be some areas of the code needing a similar update.

Refine URLs from env, create "baseUrl"

---

content/404.mdx
content/about/example.mdx
content/about/index.mdx
content/index.mdx
src/customTypes/content.ts
src/lib/build/config.ts
src/lib/seo.ts
src/pages/404.tsx
src/pages/_app.tsx
src/pages/about/[slug].tsx
src/pages/about/index.tsx
src/pages/index.tsx
src/pages/map.tsx
src/pages/metadata.tsx
src/pages/search.tsx

This refines page titles and descriptions throughout the Canopy project.
- All MDX pages now will have their `<title>` and `og:title` customizable from the `title` key in frontmatter.
- Custom content pages (not home and 404) will use the frontmatter `description` key for their meta tags. Home falls back to the summary on the canopy config, 404 doesn't have one.
- Search, Metadata, and Map routes now have hardcoded titles. This isn't working off a locale but that should be a future consideration.

Refine page title and descriptions.

---

src/components/Work/Viewer.tsx

Fixes long-standing issue with height being jammed up by relative container when canvasHeight of Clover IIIF Viewer is 100% or auto.
Looks like this now:
https://canopy-iiif-git-mathewjordan-patch-1-iiif.vercel.app/works/the-north-american-indian-being-a-series-of-volumes-picturing-and-describing-the-indians-of-the-unit
Previously:
https://canopy-iiif.github.io/canopy-iiif/works/the-north-american-indian-being-a-series-of-volumes-picturing-and-describing-the-indians-of-the-unit

Simplify height of Clover viewer, remove relative container.

---

src/components/MDX/Card.styled.ts
src/components/MDX/Card.tsx

This is a tiny change to ensure `MDX.Cards` in `ReferencedItems` have padding and a similar layout to how Masonry Cards are done.
I recognize that there is a want to move away from Stitches, but I wasn't sure the correct pattern to use now.  Happy to talk about this here and do it the new way.  I'm demoing something for donors next week and would love to pull this padding from upstream rather than maintain in my fork regardless of how code needs to look.

Pad ReferencedItems cards.

---

.github/workflows/build.yml
jest.setup.ts
package-lock.json
package.json
src/components/Card/Card.tsx
src/components/MDX/Card.test.tsx
src/components/MDX/Card.tsx
src/components/Shared/Link.test.tsx
src/components/Shared/Link.tsx

This updates testing for Card, MDXCard, and CanopyLink components and refines the GitHub workflow for testing and building of Canopy. Because these `<a>` elements will be rendered through the CanopyLink component, the relative Next.js "slug" is what is the value of the `href`, however the intended absolute URL will be built from the Next env variables and is represented in the `data-absolute-url` attribute on this same anchor element.

Enhance link testing.

---

package-lock.json
package.json
src/customTypes/canopy.ts
src/pages/_app.tsx

This adds Google Tag Manager support to Canopy. Implementers can now add a container id through the `vendor.googleTagManager.gtmId` property. This is then rendered at the app level through the Next.js `_app.tsx` and will be present on all pages.
```json
{
"collection": "https://iiif.io/api/cookbook/recipe/0032-collection/collection.json",
"vendor": {
"googleTagManager": {
"gtmId": "GTM-XXXXXXXX"
}
}
}
```
Users can also opt for direct Google Analytics support:
```json
{
"collection": "https://iiif.io/api/cookbook/recipe/0032-collection/collection.json",
"vendor": {
"googleAnalytics": {
"gaId": "G-XXXXXXXXXX"
}
}
}
```

Add GoogleTagManager support

---

config/locales/en.json
src/components/Header/Header.tsx
src/components/Hero/Hero.tsx
src/components/Search/Search.tsx

Fixes two accessibility issues:
1. Adds an `aria-label` that is missing on the search.
2. Gives alt text to the hero.
There are two more issues that we need to fix:
1. Right now, locales isn't giving a lang attribute to HTML.  I tried fixing this in `_document.tsx` but couldn't remember the best way to pull in config there.
2. There is a hidden button somewhere in the virtual dom that's making WAVE unhappy.

Accessibility issues

---

config/.default/canopy.default.json
global.d.ts
package-lock.json
package.json
src/components/Card/Card.tsx
src/components/Viewer/Ramp/index.tsx
src/components/Work/Viewer.tsx
src/customTypes/canopy.ts
src/hooks/getResourceImage.ts
src/lib/iiif/constructors/collection.js
src/pages/index.tsx

This brings in vanilla clover support for A/V focused content using the [Ramp](https://samvera-labs.github.io/ramp) player as an option. 
A `config/canopy.json` such as the following would make the Viewer on work pages utilize Ramp.
```json
{
"collection": "https://example.org/iiif/collection.json",
"components": {
"viewer": "ramp"
}
}
```
Minor update.

Support Ramp.

---

config/.default/canopy.default.json

When Flex encounters malformed data, search will fail as it can't find the unique key of the document, and indexing breaks when it tries to internally organize things. The precise error is `TypeError: a.split is not a function` inside of `Unhandled Runtime Error TypeError: a.split is not a function`.  If we simply add a default unique field to the default config, this problem doesn't seem to happen on search.
There are some other things here, but this is the biggest. If you want a collection to test with, here is one:
https://iiif.archive.org/iiif/3/terminal-escape-collection/5/collection.json

Insure Flex knows which field to use as the internal key.
